### ISSUE TITLE
naming consistency of anchor/section and link relation

### ISSUE THREAD

**Issue by dret** [indieweb/indieauth#16]
minor comment: https://www.w3.org/TR/2018/NOTE-indieauth-20180123/#redirect-url has a title and anchor that says *URL* whereas the `redirect_uri` link relation defined and described says *URI*. i'd suggest to make this consistent.

**Comment by Zegnat** [comment]
In what direction would you suggest this to be changed?

The link relation name is inherited from [OAuth 2.0 Section 4.2.1](https://tools.ietf.org/html/rfc6749#section-4.2.1), and the expected value of the relation should follow [the URL standard](https://url.spec.whatwg.org/). I would say both names are used in the right context.

IndieAuth refers to the URL standard, so that’s where people should be looking if they want to know how to handle the value of `redirect_uri`. For example when they need to add query parameters. As long as that standard is explicitly called out I do not think the value should be called anything other than a URL.

There are probably good reasons not to rename established OAuth link relations either.

**Comment by aaronpk** [comment]
@Zegnat is correct. The OAuth 2.0 parameter is `redirect_uri`, but in IndieAuth the value is always a URL.

**Comment by dret** [comment]
On 2018-01-26 22:08, Aaron Parecki wrote:
> @Zegnat <https://github.com/zegnat> is correct. The OAuth 2.0 parameter 
> is |redirect_uri|, but in IndieAuth the value is always a URL.

ok, in this case the names are well justified. i thought maybe it's just 
some inconsistent naming that can be easily fixed. thanks for the feedback!
