### ISSUE TITLE
Allowing local IP addresses in client identifiers

### ISSUE THREAD

**Issue by balloob** [indieweb/indieauth#21]
In section 3.2 Client Identifiers, it states the following:

> Additionally, hostnames MUST be domain names or a loopback interface and MUST NOT be IPv4 or IPv6 addresses except for IPv4 127.0.0.1 or IPv6 [::1].

I'm currently implementing the IndieAuth spec for [Home Assistant](https://www.home-assistant.io/). It's a home automation framework that people run locally at home. Although the computers it runs on usually have hostnames, we don't always know that. This means that users could end up navigating to the Home Assistant interface (a website) using the IP address of the host running Home Assistant. The website is a single page app that will authenticate with the backend using a Client ID following the IndieAuth spec. However, if the website has been requested over IP, both client id and redirect url will be an ip address. This is not allowed according to the spec.

[RFC1918](https://tools.ietf.org/html/rfc1918) describes Address allocation for Private Internets. [Section 3](https://tools.ietf.org/html/rfc1918#section-3) describes three ranges of IP addresses that indicate a local internet:

- 10.0.0.0        -   10.255.255.255  (10/8 prefix)
- 172.16.0.0      -   172.31.255.255  (172.16/12 prefix)
- 192.168.0.0     -   192.168.255.255 (192.168/16 prefix)

I wonder if it could be possible to relax the hostname requirement of client identifiers to include the private internet addresses.

**Comment by aaronpk** [comment]
I could see extending the limitation of the loopback address to also include the private IP ranges. I assume in that case it is extremely unlikely that the server will have an https certificate, so that's another reason to keep the limitation on the private IP ranges rather than allowing arbitrary IP addresses.

One of the benefits of the client ID being a publicly accessible web page is that the authorization server can fetch the application name and icon from that page.

![with client info](https://media.aaronpk.com/Screen-Shot-2018-07-09-05-47-34-fVaDnua7Wa.jpg)

In the case of using a private IP address, the authorization server won't be able to fetch any information about the client, so the prompt will show just the IP.

![private ip address](https://media.aaronpk.com/Screen-Shot-2018-07-09-05-46-38-6eFtpnPpjh.jpg)

The other option is to use `https://www.home-assistant.io/` as the client ID, allowing just the redirect URL to be a private IP. This breaks the rule of the client ID and redirect URL hostnames matching, so servers may show a warning like the below, but at least the application info is visible.

![redirect URL warning](https://media.aaronpk.com/Screen-Shot-2018-07-09-05-50-15-11RUZEmQrP.jpg)

**Comment by balloob** [comment]
Yeah, I agree that allowing arbitrary IP addresses would be a bad idea. Generally one cannot get certificates for it (unless you're as cool as [1.1.1.1](https://1.1.1.1/).

Forgot about the fetching of the app info. Wonder if an exception is more appropriate: client identifier is allowed to contain a local IP address if server is accessed over a local IP. Although, in that case one can also not generate a profile url that contains a DNS. And by then we're so far away from the IndieAuth spec that it's just the rules how client identifiers relate to redirect url.

I guess I'll close the issue.
